# Simple Railway configuration
[providers]
php = "8.2"
node = "18"

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]  
cmds = ["npm install && npm run build"]

[start]
cmd = "./start.sh"
