# Build configuration for Railway
providers = ["php", "node"]

[phases.build]
dependsOn = ["install"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "npm ci",
    "npm run build"
]

[phases.deploy]
cmds = [
    "php artisan migrate --force --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
